services:
  - type: web
    name: ipl-match-winner-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.address=0.0.0.0
    plan: free
